### ISSUE TITLE
Exception: Validation

### ISSUE THREAD

**Issue by cmaughan** [IG-Group/ig-webapi-dotnet-sample#3]
Out of the box, with a fresh clone, I get the following error after setting up my key/password.
Updating the nuget packages in the projects doesn't help.

I can't find a version of Validation at 2.3.0 on NuGet either.  The latest is 2.4.7, but I can't roll back to a 2.3 because there isn't one.
I've confirmed that the DLL is in the path.

In the log there is information about a 'redirect' to 2.3, so below....

Not sure what's wrong here....

System.IO.FileNotFoundException occurred
  FileName=Validation, Version=2.3.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7
  FusionLog=""
  HResult=-2147024894
  Message=Could not load file or assembly 'Validation, Version=2.3.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7' or one of its dependencies. The system cannot find the file specified.
  Source=PCLCrypto
  StackTrace:
       at PCLCrypto.RsaAsymmetricKeyAlgorithmProvider.ImportPublicKey(Byte[] keyBlob, CryptographicPublicKeyBlobType blobType)
       at IGWebApiClient.Security.Rsa..ctor(Byte[] key, Boolean intermediateConvertToBase64BeforeEncryption, Boolean isPrivateKey) in D:\Dev\ig-webapi-dotnet-sample\IGWebApiClient\Security\Rsa.cs:line 27
  InnerException: 
       FileName=Validation, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7
       FusionLog==== Pre-bind state information ===
LOG: DisplayName = Validation, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7
 (Fully-specified)
LOG: Appbase = file:///D:/Dev/ig-webapi-dotnet-sample/SampleWPFTrader/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : PCLCrypto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\Dev\ig-webapi-dotnet-sample\SampleWPFTrader\bin\Debug\SampleWPFTrader.vshost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 2.0.0.0 redirected to 2.3.0.0.
LOG: Post-policy reference: Validation, Version=2.3.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7
LOG: Attempting download of new URL file:///D:/Dev/ig-webapi-dotnet-sample/SampleWPFTrader/bin/Debug/Validation.DLL.
LOG: Attempting download of new URL file:///D:/Dev/ig-webapi-dotnet-sample/SampleWPFTrader/bin/Debug/Validation/Validation.DLL.
LOG: Attempting download of new URL file:///D:/Dev/ig-webapi-dotnet-sample/SampleWPFTrader/bin/Debug/Validation.EXE.
LOG: Attempting download of new URL file:///D:/Dev/ig-webapi-dotnet-sample/SampleWPFTrader/bin/Debug/Validation/Validation.EXE.

       HResult=-2147024894
       Message=Could not load file or assembly 'Validation, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7' or one of its dependencies. The system cannot find the file specified.
       InnerException:

**Comment by PMFTOTC** [comment]
I have the same issue, still don't know how to resolve that

**Comment by cmaughan** [comment]
Repo seems to be dead, or at least not maintained... :(

**Comment by ireay** [comment]
Repo is not dead. The Public API team provide the sample apps "as is" and maintain them as a background task.

**Comment by ireay** [comment]
Does this post help?
http://stackoverflow.com/questions/39803534/iot-hub-c-sharp-devices-sdk-crashes-with-could-not-load-file-or-assembly-valid

**Comment by cmaughan** [comment]
No, doesn't help - the question has no answer (the answer suggests installing nuget, but I have it.  It is just that the packages referenced no longer exist, and it's hard to see how to fix it.)

**Comment by johnkamau** [comment]
Solved it by setting "Copy Local" to true, for the Validation reference.

**Comment by cmaughan** [comment]
Closing since I gave up long ago and used a different broker....

**Comment by stridskoma2** [comment]
Solved for me by updating to the latest Validation nuget package

**Comment by stridskoma2** [comment]
I believe updating added this to the `app.config`, which is why it started to work:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Validation" publicKeyToken="2fc06f0d701809a7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.4.0.0" newVersion="2.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by pavellesev** [comment]
This worked for me too:

"Solved it by setting "Copy Local" to true, for the Validation reference."

**Comment by dineena** [comment]
"Copy Local"   set to true  on the validation reference got the job done for me also
